# This is a basic workflow to help you get started with Actions

name: Test, Build and Release APK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  whole_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.17.x'
      - name: Get packages
        run: flutter pub get
      - name: Run test scripts
        run: flutter test
      - name: Build current APK
        run: flutter build apk
